// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsageBreakdown = { totalTokens: number, inputTokens: number, cachedInputTokens: number, outputTokens: number, reasoningOutputTokens: number, inputTextTokens: number | null, inputImageTokens: number | null, imageOutputTokens: number | null, imageGenerationTotalTokens: number | null, partialImages: number | null, usageSource: string | null, unknownUsageDetails: Record<string, unknown> | null, };
